### PR TITLE
CI - Check for active runs before stopping VM

### PR DESCRIPTION
**Pull request by ludovicsteinbach**

### CODE REVIEW

**Comment by ludovicsteinbach** [comment]
Successful run with no active workflows: https://github.com/ansys/grantami-bomanalytics/actions/runs/8633460873/job/23666732161 -> stopping the VM

**Comment by ludovicsteinbach** [comment]
And finally a run https://github.com/ansys/grantami-bomanalytics/actions/runs/8634556244 which skips turning off.
I'll clean debug steps and re-instate commented out workflows

**Comment by ludovicsteinbach** [comment]
Run that skipped turning off: https://github.com/ansys/grantami-bomanalytics/actions/runs/8643474563/job/23696714617
Run that did not skip: https://github.com/ansys/grantami-bomanalytics/actions/runs/8643474563/job/23696972739

**Review by da1910 — APPROVED** [review]
Looks reasonable, I wish there were a way to get the list from somewhere central, like the pygranta repository but this is fine for the moment

**Pull request merged**
