### PR TITLE
Prepare for 2.2.0rc0 release

### PR DESCRIPTION
**Pull request by Andy-Grigg**
Prepare for 2.2.0rc0 release

### CODE REVIEW

**Comment by Andy-Grigg** [comment]
@ludovicsteinbach  You might be fighting a losing battle with the label. I shouldn't have changed the lockfile anyway, I'll force push this branch without that change

**Comment by Andy-Grigg** [comment]
Codacy failure seems to be a false negative

**Review by ludovicsteinbach — APPROVED** [review]
The changelog fragment is still incorrectly categorized as 'dependencies' if that's something we care about.
Other than that this looks reasonable

**Comment by Andy-Grigg** [comment]
Good point. I wonder if I can fix it by deleting the commit.

**Comment by ludovicsteinbach** [comment]
Although the openapi dependency should probably not accept pre releases anymore?

**Comment by Andy-Grigg** [comment]
> Although the openapi dependency should probably not accept pre-releases anymore?

Changing that here was the cause of the pain, because it required a change to the lockfile.  The dependabot PR didn't change it.

**Comment by Andy-Grigg** [comment]
This PR seems borked. Recreating.

**Comment by Andy-Grigg** [comment]
Recreated here #652

**Pull request closed without merging**
